In [1]:
import torch
from collections import Counter

In [2]:
# Definindo um vocabulário a partir do corpus
corpus = ['Este é o primeiro documento.', 'Este é o segundo documento.', 'Este é o terceiro documento.', 'Este é o quarto documento.']

In [3]:
# Criando um vocabulario a partir do corpus
vocab = set([word for doc in corpus for word in doc.split()])

In [4]:
# Mapeando cada palavra do vocabulario em um indice inteiro
word_to_idx = {word:i for i, word in enumerate(vocab)}
word_to_idx

{'segundo': 0,
 'Este': 1,
 'terceiro': 2,
 'documento.': 3,
 'primeiro': 4,
 'quarto': 5,
 'é': 6,
 'o': 7}

In [5]:
# Representando cada documento como um vetor de bag of words
docs_as_bow = []

for doc in corpus:
    bow_vector = torch.zeros(len(vocab))
    for word in doc.split():
        bow_vector[word_to_idx[word]] += 1
        
    docs_as_bow.append(bow_vector)

In [6]:
# Imprimindo a representação bag of words de cada documento
for i, doc in enumerate(docs_as_bow):
    print(f"Documento {i+1}:\n{doc}\n")

Documento 1:
tensor([0., 1., 0., 1., 1., 0., 1., 1.])

Documento 2:
tensor([1., 1., 0., 1., 0., 0., 1., 1.])

Documento 3:
tensor([0., 1., 1., 1., 0., 0., 1., 1.])

Documento 4:
tensor([0., 1., 0., 1., 0., 1., 1., 1.])

